version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building project...
      - echo "Hello from build stage"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
